### PR TITLE
Fix the sample file paths in the .sfz files in Extensions

### PR DESCRIPTION
**Pull request by rang3**
The file paths in .sfz are different from the ones in the Extensions directory

### CODE REVIEW

**Comment by pachadotdev** [comment]
thanks @rang3

**Comment by KaleidonKep99** [comment]
Oops I forgot to fix that before the release!
Thank you.

**Comment by pachamaltese** [comment]
@KaleidonKep99 Hi! Do you know how can I use this with qsynth? I've tried converting to sf2 but the resulting file (~650MB) hangs the synthetizer

**Comment by rang3** [comment]
My pleasure. You're welcome!

**Pull request merged**
